serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::606876783566:role/iceberg-demo-mwaa-execution

config:
  logging:
    remote_logging: "True"
    remote_base_log_folder: "s3://vna-lab-data-storage/logs/airflow"
    remote_log_conn_id: "aws_default"
    encrypt_s3_logs: "False"
